### ISSUE TITLE
Bug: deployment.yaml: error converting YAML to JSON: yaml: line 28: could not find expected ':'

### ISSUE THREAD

**Issue by MitchelNijdam-Rockstars** [mock-server/mockserver#1166]
**Describe the issue**
Helm deployment fails due to the following error:

> Error: YAML parse error on mockserver/templates/deployment.yaml: error converting YAML to JSON: yaml: line 28: could not find expected ':'

If you look at line 28 (by running `helm template mockserver . --debug`), there is a space missing after `image`:

```yaml
...
 spec:
      serviceAccountName: default
      containers:
        - name: mockserver
          image:mockserver/mockserver:mockserver-snapshot
...
```

Looks like this commit introduced the issue:

https://github.com/mock-server/mockserver/commit/e50dfa323d86c4ccefd0e04f87f8041df0598285#diff-f2a0902300a74e229b6d4ea664c9d01c2b34ae8ec306ef1f315af3604953a29dR32

**What you are trying to do**
Manually deploy the helm chart.

**MockServer version**
5.11.2

**To Reproduce**

1. Go to the `helm/mockserver` folder.
2. execute `helm template mockserver . --debug`

**Expected behaviour**
Helm chart installs correctly.

**Proposed solution**
In `helm/mockserver/templates/deployment.yaml`, change line 32:

```
image: {{ if .Values.image.repositoryNameAndTag }}{{ .Values.image.repositoryNameAndTag }}{{- else }}{{ .Values.image.repository }}/mockserver:mockserver-{{- if .Values.image.snapshot }}snapshot{{- else }}{{ .Chart.Version }}{{- end }}{{- end }}
```
