### ISSUE TITLE
SERVER_PORT option no longer works

### ISSUE THREAD

**Issue by busches** [mock-server/mockserver#1172]
**Describe the issue**
When upgrading from 5.10.0 to beyond, the `SERVER_PORT` environment variable no longer sets the port, despite the documentation stating it does.

**What you are trying to do**
Change the default port mockserver runs on, so there's no conflicts inside the docker network.

**MockServer version**
5.11.0, 5.11.1, 5.11.2, and latest

**To Reproduce**
Via Docker-Compose:

```yml
version: '2.4'
services:
  mockServer:
    image: mockserver/mockserver:mockserver-5.11.2
    ports:
      - 1080:1090
    environment:
      SERVER_PORT: 1090
```

**Expected behaviour**
Mockserver would start on 1090, like it does on 5.10.0.

**MockServer Log**
```
 2022-02-07 15:15:52 5.11.3-SNAPSHOT INFO 1080 started on port: 1080
```
