### ISSUE TITLE
Templating in docker 

### ISSUE THREAD

**Issue by chameleon82** [mock-server/mockserver#1218]
**Describe the issue**

I would like to enable templating in docker and  to use `--global-response-templating` in docker container 

**What you are trying to do**
Description of what you are trying to do so we can understand the context of the problem

**MockServer version**
 5.12.0

**To Reproduce**

Steps to reproduce the issue:

1. How you are running MockServer (i.e maven plugin, docker, etc)

```yml
 image: mockserver/mockserver:mockserver-5.12.0
    ports:
      - "1080:1080"
    environment:
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/**.json
    volumes:
      - ./config:/config
    command: --global-response-templating
```
2. Code you used to create expectations

```json
[
  {
    "httpRequest" : {
      "method" : "GET",
      "path" : "*"
    },
    "httpResponse" : {
      "bodyFileName": "Response.json",
      "transformers": ["response-template"],
      "statusCode": 200
    }
  }
]
```

4. What error you saw

```log
 schema validation errors:

  2 errors:
   - $.httpResponse.bodyFileName: is not defined in the schema and the schema does not allow additional properties
   - $.httpResponse.transformers: is not defined in the schema and the schema does not allow additional properties
```

**Expected behaviour**

Expect that plugin will be enabled

**MockServer Log**

```log
 schema validation errors:

  2 errors:
   - $.httpResponse.bodyFileName: is not defined in the schema and the schema does not allow additional properties
   - $.httpResponse.transformers: is not defined in the schema and the schema does not allow additional properties
```
