### ISSUE TITLE
add configmap to main helm chart

### ISSUE THREAD

**Issue by heydonovan** [mock-server/mockserver#1272]
I'm taking over our mockserver setup, and read we are instructed to install two different helm installations. The main `mockserver` helm chart, and then `mockserver-config` one. Any thoughts on adding a configmap template to the main one? That way its just a single helm install/upgrade.

**Comment by jamesdbloom** [comment]
I'm not sure that is technically possible.  As far as I'm aware this is a known limitation of helm charts.

Do you have any suggestions as to how this could be implemented?

**Comment by jamesdbloom** [comment]
I'll review the latest helm support and check what is already implement and add an integration test to cover this use case

**Comment by jamesdbloom** [comment]
This has been implemented. The main `mockserver` Helm chart now includes an optional `configmap.yaml` template that can be enabled via `app.config.enabled=true` in values.

**What changed:**

1. **New `configmap.yaml` template** in `helm/mockserver/templates/` — conditionally creates a ConfigMap when `app.config.enabled=true`
2. **New values** in `values.yaml`:
   - `app.config.enabled` (default: false) — set true to create ConfigMap from inline values
   - `app.config.properties` — content of `mockserver.properties`
   - `app.config.initializerJson` — content of `initializerJson.json`
   - `app.config.extraFiles` — map of additional filenames to content (e.g. TLS certs)
3. **Bug fix** in `deployment.yaml` — the `MOCKSERVER_PROPERTY_FILE` env var is now correctly set when inline config is enabled (previously referenced the undefined `app.mountConfigMap` value)

**Example — single chart install with configuration:**

```yaml
app:
  config:
    enabled: true
    properties: |
      mockserver.initializationJsonPath=/config/initializerJson.json
      mockserver.enableCORSForAPI=true
    initializerJson: |
      [{"httpRequest": {"path": "/example"}, "httpResponse": {"body": "response"}}]
```

```bash
helm upgrade --install --namespace mockserver -f values.yaml mockserver helm/mockserver
```

Both patterns are supported — inline config (new, recommended) and external ConfigMap (existing behavior, unchanged). The separate `mockserver-config` chart is retained as a reference example.
