### ISSUE TITLE
Resusable examples ($ref) not converted by mock server

### ISSUE THREAD

**Issue by Ellosaur** [mock-server/mockserver#1474]
**Describe the issue**
Example responses that reference [reusable examples](https://swagger.io/docs/specification/adding-examples/) (`$ref`) do not return the expected response.

**What you are trying to do**
Have reusable examples to enrich the data returned from our mock, while not having to copy/paste lots of similar reponse objects into different endpoints.

**MockServer version**
latest docker tag (5.14.0)

**To Reproduce**
Create a swagger that contains an examples section in components:

```yaml
  examples: 
    firstTaskExample:
      value:
        attributes:
          taskStatus: 
            code: 2006
            description: "Pending"
          createdTime: "2019-10-10T20:20:20Z"
          lastUpdatedTime: "2019-10-11T20:20:20Z"

    secondTaskExample:
      value:
        attributes:
          taskStatus: 
            code: 1000
            description: "Completed"
          createdTime: "2019-10-10T20:20:20Z"
          lastUpdatedTime: "2019-10-11T21:20:20Z"
```

Reference them in other objects:

```yaml
    taskListResponse:
      title: taskListResponse
      type: object
      properties:
        data:
          type: array
          items:
            $ref: "#/components/schemas/taskSingleResponse"
          example:
            - $ref: '#/components/examples/firstTaskExample/value'
            - $ref: '#/components/examples/secondTaskExample/value'
 ```

Ultimately reference them as an example response

```yaml
  /tasks:
    get:
      summary: Get a list of tasks by the tasktype and organisation
      responses:
        "200":    # status code
          description: Success - a list of tasks
          content:
            application/vnd.api+json:
              schema:
                $ref: "#/components/schemas/taskListResponse"
```

Observe in [Swagger Editor](https://editor.swagger.io/) the example response correctly rendered:

```json
"data": [
    {
      "attributes": {
        "taskStatus": {
          "code": 2006,
          "description": "Pending"
        },
        "createdTime": "2019-10-10T20:20:20Z",
        "lastUpdatedTime": "2019-10-11T20:20:20Z"
    },
    {
      "attributes": {
        "taskStatus": {
          "code": 1000,
          "description": "Completed"
        },
        "createdTime": "2019-10-10T20:20:20Z",
        "lastUpdatedTime": "2019-10-11T21:20:20Z"
    }]
```
Initialise mock server from the same swagger and call the endpoint to get unexpected response

```json
{
  "data" : [ {
    "$ref" : "#/components/examples/firstTaskExample/value"
  }, {
    "$ref" : "#/components/examples/secondTaskExample/value"
  } ]
}
```

**Expected behaviour**
The mock server response should be the same as in the swagger editor

**MockServer Log**
No clues here
