### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by stanosamek** [mock-server/mockserver#1741]
Hi, 

we have a problem with OutOfMemoryError: Java heap space after loading expectations and running some tests. We are using mockserver in version 5.13.2 and we are running server with helm chart on Kubernetes.  We were trying to fix issue with switching storing expectations into file system with parameter mockserver.persistExpectations=true but mockserver is still using approx. 600MB and failing on heap space. 

We were also trying to add jvmOptions into values.yaml. In deployment we can see environment property JVM_OPTIONS. 

```
spec:
  containers:
    - env:
      - name: MOCKSERVER_LOG_LEVEL
         value: INFO
      - name: SERVER_PORT
         value: '1080'
      - name: JVM_OPTIONS
         value: '-Xms1G -Xmx2G'
    image: nexus/ps-sq002-pub/mockserver/mockserver:5.13.2
```

How can we increase JVM heap for mockserver?

Thank you

**Comment by tstonely-mt** [comment]
I'm also seeing some memory pressure issues when running on k8s via the helm chart, the memory usage looks very leaky. 
![image](https://github.com/mock-server/mockserver/assets/52451964/ed5bc99d-c7c2-4010-9506-ba91b1a0e7f8)

**Comment by thomasjoulin** [comment]
@stanosamek @tstonely-mt did you ended up finding a solution? We're seeing the same problem here...

**Comment by tstonely-mt** [comment]
@thomasjoulin Yes, in the end we ended up setting the memory config properties. I think it was the two below. Memory usage stabilised after that :+1: 

```
# maximum number of expectations held in the in-memory ring buffer
mockserver.maxExpectations=1000

# maximum number of log entries to hold in memory, this include recorded requests, expectation match failures and other log entries
mockserver.maxLogEntries=5000
```

**Comment by jamesdbloom** [comment]
**Resolution: Configuration issue — documented**

As resolved in the comments, the OutOfMemoryError is caused by the default dynamic sizing of `maxExpectations` and `maxLogEntries` which scales based on available heap at startup. For smaller heap sizes, set explicit limits:

```
docker run -e MOCKSERVER_MAX_EXPECTATIONS=100 \
           -e MOCKSERVER_MAX_LOG_ENTRIES=100 \
           -e JVM_OPTIONS="-Xmx256m" \
           mockserver/mockserver
```

**For Helm charts**, set JVM options via environment variables in `values.yaml`:
```yaml
env:
  - name: JVM_OPTIONS
    value: "-Xmx512m"
  - name: MOCKSERVER_MAX_EXPECTATIONS
    value: "500"
  - name: MOCKSERVER_MAX_LOG_ENTRIES
    value: "500"
```

A memory tuning guide has been added to the [Performance Configuration documentation](https://www.mock-server.com/mock_server/performance.html) with recommended values for different heap sizes.
