### ISSUE TITLE
[Bug] No way to implement docker-compose health-check

### ISSUE THREAD

**Issue by aokhonchenko** [mock-server/mockserver#1895]
I am trying to do simple thing - check readiness probe with docker-compose.

tag - 5.15.0

```

  mockserver:
    image: mockserver/mockserver:5.15.0
    ports:
      - "17777:1080"
    environment:
      MOCKSERVER_PORT_NUMBER: 1080
      MOCKSERVER_LIVENESS_HTTP_GET_PATH: "/liveness/probe"
      MOCKSERVER_INITIALIZATION_JSON_PATH: "/stubs/*.json"
      MOCKSERVER_WATCH_INITIALIZATION_JSON: true
      MOCKSERVER_LOG_LEVEL: DEBUG
    healthcheck:
#      test: curl --fail http://localhost:1080/liveness/probe || exit 1
      test: wget --no-verbose --tries=1 --spider http://localhost:1080/liveness/probe || exit 1
      interval: 60s
      retries: 5
      start_period: 5s
      timeout: 10s
    volumes:
      - type: bind
        source: ./src/test/resources/stubs
        target: /stubs
        read_only: true
```

After about 60s server fails.

**Comment by kasir-barati** [comment]
Any update? or if it is not possible please let us know by adding a section in docker hub so people know that it does not have something like that.

I also tried to exec inside it and check what is available but it seems this image has a very fundamental issue. `$PATH` is unknown. In other word `curl`, `wget` or any kind of command in general cannot be used. Try to exec into it like this: 

```cmd
docker exec -it container_id /bin/sh
# or
docker exec -it container_id /bin/bash
# or
docker exec -it container_id bash
```

So I guess the problem lies in `$PATH`.

**Comment by ae-naltun** [comment]
Currently, having the same issue.  When can we expect this to be fixed?

**Comment by jamesdbloom** [comment]
## Docker Health Checks with Distroless Images

MockServer Docker images are based on [distroless](https://github.com/GoogleContainerTools/distroless) containers for security and minimal attack surface. **Distroless images do not include shell utilities like `curl` or `wget`**, which is why your health check is failing.

### Solution 1: TCP-Based Health Check (Recommended)

Use a TCP connection test instead of HTTP:

```yaml
version: "2.4"
services:
  mockserver:
    image: mockserver/mockserver:5.15.0
    ports:
      - "1080:1080"
    environment:
      MOCKSERVER_LIVENESS_HTTP_GET_PATH: "/liveness/probe"
    healthcheck:
      test: ["CMD-SHELL", "timeout 1 bash -c ':> /dev/tcp/localhost/1080' || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s
```

### Solution 2: External HTTP Health Check

Use a separate container or your orchestration platform (Kubernetes, ECS, etc.) to perform HTTP health checks externally:

```yaml
version: "2.4"
services:
  mockserver:
    image: mockserver/mockserver:5.15.0
    ports:
      - "1080:1080"
    environment:
      MOCKSERVER_LIVENESS_HTTP_GET_PATH: "/liveness/probe"
  
  healthcheck:
    image: curlimages/curl:latest
    depends_on:
      - mockserver
    command: >
      sh -c "while true; do
        curl -f http://mockserver:1080/liveness/probe || exit 1;
        sleep 10;
      done"
```

### Why Distroless?

Distroless images minimize vulnerabilities and reduce the attack surface by including only the JVM and MockServer code—no shell, package managers, or other utilities. This is a security best practice for production containers.

---

I've updated the Docker documentation with health check examples: https://github.com/mock-server/mockserver/commit/81ec09551d5cb5b6faed9e833aec5ddbaeb57f19

See the full documentation at https://www.mock-server.com/mock_server/running_mock_server.html#docker_healthcheck

Closing this issue as the question is now answered and documented.
