### ISSUE TITLE
Can't configure the server port in docker-compose [5.7.2]

### ISSUE THREAD

**Issue by nicolasberthet** [mock-server/mockserver#696]
Hello,

I am trying to configure a mock server and change the default server port. But unfortunately, the tip that you gave in this issue doesn't work for version 5.7.2 : [https://github.com/mock-server/mockserver/issues/585](https://github.com/mock-server/mockserver/issues/585)

Do I have to create my own docker image changing the default script args ?

```
toto: 
    image: jamesdbloom/mockserver:mockserver-5.7.2
    command: /opt/mockserver/run_mockserver.sh -serverPort 80
    user: root
    environment:
      LOG_LEVEL: "DEBUG"
```
Thanks.

Regards,

Nicolas

**Comment by jamesdbloom** [comment]
The syntax you need is as follows:

```yaml
 mockServer:
   image: mockserver/mockserver:mockserver-5.7.2
   command: -serverPort 80
   user: root
   ports:
   - 1080:1090
   environment:
      LOG_LEVEL: "DEBUG"
```

I will update the documentation on the website to provide an example of this so that it is clearer.
