### ISSUE TITLE
Body type "JSON_SCHEMA" complains about incorrect json schema

### ISSUE THREAD

**Issue by DazKins** [mock-server/mockserver#701]
I'm trying to mock a PATCH request with a JSON schema on the request body:

```javascript
client.mockAnyResponse({
    "httpRequest": {
        "method": "PATCH",
        "body": {
            "type": "JSON_SCHEMA",
            "value": JSON.stringify({
                "type": "object",
                "properties": {
                    "given_name": {
                        "type": "string"
                    },
                    "middle_name": {
                        "type": "string"
                    },
                    "family_name": {
                        "type": "string"
                    },
                    "language": {
                        "type": "string",
                        "minLength": 2,
                        "maxLength": 2
                    },
                    "country": {
                        "type": "string",
                        "minLength": 2,
                        "maxLength": 2
                    },
                    "mobile": {
                        "type": "string"
                    }
                },
                "required":[]
            })
        },
        "path": "/accounts/" + UUID_regex + "/profile"
    },
    "httpResponse": {
        "statusCode": 204
    }
}).then(function () {}, function (err) {
    console.log(err);
});
```

It gives me the error:

`Schema must either be a path reference to a *.json file or a json string`

I don't see what can be wrong with this?

It seems to follow exactly the template given [here](https://5-1.mock-server.com/mock_server/creating_expectations.html)

**Comment by jamesdbloom** [comment]
It looks like the documentation on that page is slight out of date which I will fix although the code does still support the `value` field due to limitations in the way JSON schema validation works in some libraries with `oneOf` the field names needed to be different for each type of body.  I must have missed updating that page, I double-check them all now.

The schema for that object is:

```json
 {
    "type": "object",
    "additionalProperties": false,
    "properties": {
        "not": {
            "type": "boolean"
        },
        "type": {
            "enum": [
                "JSON_SCHEMA"
            ]
        },
        "jsonSchema": {
            "type": "string"
        }
    }
},
```

Also found in Swagger Hub as :

```yaml
        - type: object
          description: "json schema body matcher"
          additionalProperties: false
          properties:
            not:
              type: boolean
            type:
              enum:
                - JSON_SCHEMA
            jsonSchema:
              type: string
```
https://app.swaggerhub.com/apis/jamesdbloom/mock-server-openapi/5.7.x#/Body
