### ISSUE TITLE
It is impossible to provide array JSON response in the configuration mapping

### ISSUE THREAD

**Issue by mykola-mokhnach** [mock-server/mockserver#824]
Hello,

We experience the following issue while running the mockserver. In our architecture we need to mock an endpoint, that returns `application/json` response of array type. Although, the parser fails to properly recognise such values, so we need to put the whole example JSON array into a string, escape quotes, etc, which looks weird and is not very practical/easy to read. Here is an example:

```json
  {
    "httpRequest": {
      "method": "GET",
      "path": "/app-center/v0.1/apps"
    },
    "httpResponse": {
      "statusCode": 200,
      "body": {
        "type": "JSON",
        "json": "[  { \"id\": \"fd006680-dcd7-438e-839e-67f50d9ccdef\"  }   ]",
        "contentType": "application/json"
      }
    }
  },
```

works as expected, while 

```json
  {
    "httpRequest": {
      "method": "GET",
      "path": "/app-center/v0.1/apps"
    },
    "httpResponse": {
      "statusCode": 200,
      "body": {
        "type": "JSON",
        "json": [
          { "id": "fd006680-dcd7-438e-839e-67f50d9ccdef"  }
        ],
        "contentType": "application/json"
      }
    }
  },
```

or

```json
  {
    "httpRequest": {
      "method": "GET",
      "path": "/app-center/v0.1/apps"
    },
    "httpResponse": {
      "statusCode": 200,
      "body": [
          { "id": "fd006680-dcd7-438e-839e-67f50d9ccdef"  }
       ]
    }
  },

```

fail with parsing error in the pod logs. 

Chart version: 5.8.0

**Comment by jamesdbloom** [comment]
I would suggest using a more recent version of MockServer the current version is 5.11.1, 5.8.0 is pretty old and I think your issue was already fixed.

**Comment by jamesdbloom** [comment]
Can you retest with the latest version and confirm if you still have an issue?

**Comment by mykola-mokhnach** [comment]
Thanks for the quick response @jamesdbloom

I've upgraded the chart to version 5.11.1 and it does not complain to the format of the configuration json anymore. Hoverer, other nock handlers stopped working as well. Did I miss some important updates?

The config entry that stopped working looks like

```json
  {
    "httpRequest": {
      "method": "GET",
      "path": "/user-service/v1/services/users/[^/]+/"
    },
    "httpResponse": {
      "statusCode": 200,
      "body": {
        "id": "a0966cc8779d487182aaaa5b2c0a21ea",
     }
  }
```

and in the logs from v 5.11.1 I observe:

```
2020-08-10 12:33:22 5.11.1 INFO 1080 no expectation for:

  {
    "method" : "GET",
    "path" : "/user-service/v1/services/users/test/",
    "headers" : {
      "Host" : [ "app-integration-service-mockserver.default:1080" ],
      "Accept" : [ "*/*" ],
      "Accept-Encoding" : [ "gzip, deflate" ],
      "User-Agent" : [ "Python/3.7 aiohttp/3.6.2" ],
      "content-length" : [ "0" ]
    },
    "keepAlive" : true,
    "secure" : false
  }

 returning response:

  {
    "statusCode" : 404,
    "reasonPhrase" : "Not Found",
    "headers" : {
      "connection" : [ "keep-alive" ],
      "content-length" : [ "0" ]
    }
  }
```

**Comment by mykola-mokhnach** [comment]
to me it looks like it stopped loading the mocks config file. The config map looks like

```
{{- if .Values.mockserver.app.mountConfigMap -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: mockserver-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  mockserver.properties: |
{{ .Files.Get "static/mockserver.properties" | printf "%s" | indent 4 }}
  initializerJson.json: |
{{ .Files.Get "static/initializerJson.json" | printf "%s" | indent 4 }}
{{- end }}
```
