### ISSUE TITLE
encoding issue with mockserver 

### ISSUE THREAD

**Issue by altfatterz** [mock-server/mockserver#903]
Steps to reproduce:

1. Start the mockserver via:

```bash
$ docker run -d --rm -p 1080:1080 mockserver/mockserver:mockserver-5.11.1
```

2. create a simple expectation:

```yaml
{
  "httpRequest": {
    "method": "GET",
    "path": "/v1/api/foo"
  },
  "httpResponse": {
    "body": "{\"city\":\"Zürich\"}",
    "headers": {
      "Content-Type": [
        "application/json; charset=utf-8"
      ]
    },
    "statusCode": 200
  }
}
```

```bash
$ http put http://localhost:1080/mockserver/expectation @foo.json
```

response:

```yaml
HTTP/1.1 201 Created
connection: keep-alive
content-length: 412
content-type: application/json; charset=utf-8
version: 5.11.1

[
    {
        "httpRequest": {
            "method": "GET",
            "path": "/v1/api/foo"
        },
        "httpResponse": {
            "body": "{\"city\":\"ZÃ¼rich\"}",             // <-- encoding issue
            "headers": {
                "Content-Type": [
                    "application/json; charset=utf-8"
                ]
            },
            "statusCode": 200
        },
        "id": "06c2fbe1-fa90-4d71-ba31-d136c33a5109",
        "priority": 0,
        "timeToLive": {
            "unlimited": true
        },
        "times": {
            "unlimited": true
        }
    }
]
```

3. test the expectation:

```bash
$ http :1080/v1/api/foo

HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
connection: keep-alive
content-length: 20

{
    "city": "ZÃ¼rich"  // <-- encoding issue
}
```
Any idea how to fix this?
