### ISSUE TITLE
Specifying configuration file location does not work anymore with docker-compose and mock-server version 5.11.x

### ISSUE THREAD

**Issue by latuszek** [mock-server/mockserver#964]
**Describe the issue**
Specifying configuration file location does not work anymore with docker-compose and mock-server version 5.11.x.

**What you are trying to do**
Run mock-server via docker-compose and use custom configuration properties.

**MockServer version**
5.11.0, 5.11.1, 5.11.2

**To Reproduce**
```yaml
version: "3.5"
services:
  mock-server:
    image: mockserver/mockserver:mockserver-5.11.2
    ports:
      - 1090:1080
    environment:
      MOCKSERVER_PROPERTY_FILE: /opt/mock-server/config.properties
    volumes:
      - type: bind
        source: ./mock-server
        target: /opt/mock-server
```
Plus any config.properties file e.g.:
```properties
mockserver.initializationJsonPath=/opt/mock-server/init.json
```

**Expected behaviour**
This should work as in the 5.10.0 or at least be described properly in [the documentation](https://www.mock-server.com/where/docker.html#docker_compose).
