### ISSUE TITLE
/mockserver/dashboard doesn't work under reverse proxy

### ISSUE THREAD

**Issue by Tolyandre** [mock-server/mockserver#997]
**Describe the issue**
I have MockServer deployed in k8s and exposed through Nginx reverse proxy. Url to MockServer looks like `http://company_internal_domain/sales-mocks`.

Mocking functionality works as expected, but Dashboard `http://company_internal_domain/sales-mocks/mockserver/dashboard` doesn't work. Dashboard html is loaded property, but links to css and js are broken, they miss "sales-mocks" path.

**MockServer version**
Docker image `mockserver/mockserver:mockserver-5.11.2`

**To Reproduce**
I prepared a docker-compose snippet with this nginx config:

nginx.conf
```nginx
events {
}

http {
    server {
        server_name mockserver;

        location /sales-mocks {
            proxy_set_header X-Forwarded-Prefix /sales-mocks;
            proxy_pass http://mockserver:1080;
            rewrite ^/sales-mocks(.*)$ $1 break;
        }

        listen 80;
    }
}
```

docker-compose.yaml
```yaml
version: "3"
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80

  mockserver:
    image: mockserver/mockserver:mockserver-5.11.2
```
Then run `docker-compose up` and browse`http://localhost:8080/sales-mocks/mockserver/dashboard`

Blank page with errors appears
![image](https://user-images.githubusercontent.com/2414704/110846393-27a19080-82c5-11eb-90c1-218536bbcc95.png)

**Expected behaviour**
Links to css and js are respect path, e.g. contains "sales-mocks"

---
 
I suggest two ways to fix this:
- use relative paths to css and js instead of absolute. E.g. `/mockserver/dashboard/static/css/main.477cab2a.chunk.css` should be `static/css/main.477cab2a.chunk.css`
- or respect non-standard commonly used `x-forwarded-prefix` header. It contains base path, which can be put in <base> https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base
